### ISSUE TITLE
[ Pixel 6 - Android 14 ] impossible to open app 

### ISSUE THREAD

**Issue by Aarqw12** [Arnova8G2/Gcam_8.7.250.44#67] opened 2023-06-19 23:57 UTC
Phone : pixel 6 oriole 

Android : 14 UPB3.230519.014

Issue : impossible to open app its Ask please enable camera Access in settings and I have already given , api 34 support no added in gcam mod ?

**Comment by Arnova8G2** [comment] 2023-06-20 06:56
@Aarqw12 , can you make a log ?

Use shortcut, reproduce crash and share zip file ( /gcam/log )
![Screenshot_2023-04-17-23-08-15-858_app lawnchair debug-edit](https://user-images.githubusercontent.com/40323300/232611415-1c537adf-fc56-4891-940f-4b83b83308bb.jpg)

**Comment by Aarqw12** [comment] 2023-06-20 09:23
ha sad its no work shortcut ! ok I have do logcat from adb + screencord for the crash

[logcat.txt](https://github.com/Arnova8G2/Gcam_8.7.250.44/files/11798332/logcat.txt)

https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/38363978/328313d8-cb7a-4dc5-ab1d-7f0aab7b453c

**Comment by cyberphantom52** [comment] 2023-06-20 21:14
Checking the permissions using dumpsys i get the following
`redfin:/ # dumpsys package arn.android.gcam.beta | grep granted=false                                                                                                                                                                                        
      android.permission.WRITE_SETTINGS: granted=false
      android.permission.MANAGE_EXTERNAL_STORAGE: granted=false
      android.permission.SYSTEM_CAMERA: granted=false
      android.permission.INSTALL_PACKAGE_UPDATES: granted=false`

**Comment by Aarqw12** [comment] 2023-06-20 21:54
> Checking the permissions using dumpsys i get the following
> 
> ```shell
> redfin:/ # dumpsys package arn.android.gcam.beta | grep granted=false
> android.permission.WRITE_SETTINGS: granted=false
> android.permission.MANAGE_EXTERNAL_STORAGE: granted=false
> android.permission.SYSTEM_CAMERA: granted=false
> android.permission.INSTALL_PACKAGE_UPDATES: granted=false
> ```

Yes I have seen that in log too the problems is I have granded it ! ( See screen record)

**Comment by Arnova8G2** [comment] 2023-06-21 06:14
@Aarqw12 , I will send you a test version, to see

**Comment by Aarqw12** [comment] 2023-06-21 09:30
> @Aarqw12 , I will send you a test version, to see

Ok  👍

**Comment by Arnova8G2** [comment] 2023-06-23 06:31
@Aarqw12 test this : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.4-Beta3

**Comment by Aarqw12** [comment] 2023-06-23 07:45
> @Aarqw12 test this : https://github.com/Arnova8G2/Gcam_8.7.250.44/releases/tag/V8.4-Beta3

Same result 

[logcat](https://drive.proton.me/urls/B1QQT9SN50#JH2UhpUCbItz)

**Comment by Arnova8G2** [comment] 2023-06-23 08:23
@Aarqw12 , Another mistake to fix

**Comment by Arnova8G2** [comment] 2023-06-28 06:37
@Aarqw12 test version : https://e.pcloud.link/publink/show?code=XZLDBfZ9d6K0b2pXnmrJlVebNi0M4AR3qGk

**Comment by Aarqw12** [comment] 2023-06-28 09:35
> @Aarqw12 test version : https://e.pcloud.link/publink/show?code=XZLDBfZ9d6K0b2pXnmrJlVebNi0M4AR3qGk

Same result again

[logcat.txt](https://drive.proton.me/urls/EDVA90CP60#BPLI0HOLSyQG)

**Comment by Arnova8G2** [comment] 2023-06-28 14:23
> > @Aarqw12 test version : https://e.pcloud.link/publink/show?code=XZLDBfZ9d6K0b2pXnmrJlVebNi0M4AR3qGk
> 
> Same result again
> 
> [logcat.txt](https://drive.proton.me/urls/EDVA90CP60#BPLI0HOLSyQG)

If you can access setting by shortcut
to disable "camera.lancet_enabled"

![Screenshot_2023-06-28-16-20-09-067_app lawnchair debug-edit](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/658c7d30-36f4-4cef-b0f2-43a46de5daf5)

**Comment by Aarqw12** [comment] 2023-06-28 14:31
> > > @Aarqw12 test version : https://e.pcloud.link/publink/show?code=XZLDBfZ9d6K0b2pXnmrJlVebNi0M4AR3qGk
> > 
> > 
> > Same result again
> > [logcat.txt](https://drive.proton.me/urls/EDVA90CP60#BPLI0HOLSyQG)
> 
> If you can access setting by shortcut to disable "camera.lancet_enabled"
> 
> ![Screenshot_2023-06-28-16-20-09-067_app lawnchair debug-edit](https://user-images.githubusercontent.com/40323300/249513834-658c7d30-36f4-4cef-b0f2-43a46de5daf5.jpg)

Yes I Can access by shortcut and I have disabled it but it's still no resolve it

**Comment by Arnova8G2** [comment] 2023-06-28 14:44
@Aarqw12 , your logcat indicates loading of lancet in errors

![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/67e31c25-97bc-46c8-a4df-7b2dd26c9e40)

I'll disable this lancet loading and send you

**Comment by Arnova8G2** [comment] 2023-06-28 21:45
@Aarqw12 I enabled loading of lancet files with "camera.lancet_enabled"

disable it so that the files do not load
https://e.pcloud.link/publink/show?code=XZAxWfZEJ6sXNrONcHiylR9vaJcjyqasUNk

**Comment by Aarqw12** [comment] 2023-06-28 22:12
> @Aarqw12 I enabled loading of lancet files with "camera.lancet_enabled"
> 
> disable it so that the files do not load https://e.pcloud.link/publink/show?code=XZAxWfZEJ6sXNrONcHiylR9vaJcjyqasUNk

Ok camera.lancet is disabled in developers setting.

New logcat [ no fixed at the moment ]

[logcat](https://drive.proton.me/urls/0SCHQSQHB0#-Mo82SIYlsPz)

**Comment by Arnova8G2** [comment] 2023-06-29 12:03
@Aarqw12 Hoping this is last error
https://e.pcloud.link/publink/show?code=XZOasfZ6gaQR756lSffSU8u9PB6ff8FjtMk

Thanks for your help on pixels.

**Comment by Aarqw12** [comment] 2023-06-29 12:16
> @Aarqw12 Hoping this is last error https://e.pcloud.link/publink/show?code=XZOasfZ6gaQR756lSffSU8u9PB6ff8FjtMk
> 
> Thanks for your help on pixels.

It's no last error,  🔜  support for pixel a14 ^^

Logcat-2 [logcat-2](https://drive.proton.me/urls/GZ0ZBC4G54#ln7MbAp_v-93)

**Comment by Arnova8G2** [comment] 2023-06-29 13:00
> > @Aarqw12 Hoping this is last error https://e.pcloud.link/publink/show?code=XZOasfZ6gaQR756lSffSU8u9PB6ff8FjtMk
> > Thanks for your help on pixels.
> 
> It's no last error, 🔜 support for pixel a14 ^^
> 
> Logcat-2 [logcat-2](https://drive.proton.me/urls/GZ0ZBC4G54#ln7MbAp_v-93)
 is disable "camera.lancet_enabled" ?
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/b91670c1-a6b9-4221-89f1-9bd5b599b077)

**Comment by Aarqw12** [comment] 2023-06-29 13:03
> > > @Aarqw12 Hoping this is last error https://e.pcloud.link/publink/show?code=XZOasfZ6gaQR756lSffSU8u9PB6ff8FjtMk
> > > Thanks for your help on pixels.
> > 
> > 
> > It's no last error, 🔜 support for pixel a14 ^^
> > Logcat-2 [logcat-2](https://drive.proton.me/urls/GZ0ZBC4G54#ln7MbAp_v-93)
> > is disable "camera.lancet_enabled" ?
> > ![image](https://user-images.githubusercontent.com/40323300/249777238-b91670c1-a6b9-4221-89f1-9bd5b599b077.png)

Yes checked before test it's disabled in dev setting camera.lancet_enabled

**Comment by cyberphantom52** [comment] 2023-06-29 14:31
@Arnova8G2 i checked with two different gcams on my phone, the difference between you'r version and a version that works is are the following permissions
```
[phantom@rog ~]$ adb shell su -c dumpsys package com.google.android.GoogleCameraLMCR18 | grep -i granted=false
      android.permission.WRITE_SETTINGS: granted=false
      android.permission.MANAGE_EXTERNAL_STORAGE: granted=false
      com.google.android.elmyra.permission.CONFIGURE_ASSIST_GESTURE: granted=false
        android.permission.POST_NOTIFICATIONS: granted=false, flags=[ USER_SET|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
[phantom@rog ~]$ adb shell su -c dumpsys package arn.android.gcam.beta | grep -i granted=false
      android.permission.WRITE_SETTINGS: granted=false
      android.permission.MANAGE_EXTERNAL_STORAGE: granted=false, flags=[ USER_SET]
      android.permission.SYSTEM_CAMERA: granted=false
      android.permission.INSTALL_PACKAGE_UPDATES: granted=false
        android.permission.POST_NOTIFICATIONS: granted=false, flags=[ USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED]
```

EDIT: I should probably mention that the other gcam is 8.4

**Comment by cyberphantom52** [comment] 2023-06-29 14:51
@Arnova8G2 i found the fix
I changed this line
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />`
in AndroidManifest.xml to
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

Now the camera is working fine.

Since we are supposed to use READ_MEDIA_IMAGES and READ_MEDIA_VIDEOS in A13 and above, i think it's some missing logic in the code part.

EDIT:
I found the following check in the code
```
private final boolean checkPermission() {
        return this.d.checkSelfPermission("android.permission.WRITE_EXTERNAL_STORAGE") == 0 && this.d.checkSelfPermission("android.permission.READ_EXTERNAL_STORAGE") == 0;
    }
```

It seems to be checking for `READ_EXTERNAL_STORAGE` regardless of the API version

**Comment by Arnova8G2** [comment] 2023-06-29 17:08
@cyberphantom52 , Thanks no warning, I had not checked with SDK updates in android studio
![image](https://github.com/Arnova8G2/Gcam_8.7.250.44/assets/40323300/464cf498-bd74-45f4-b5fd-09805b0fae41)

**Comment by Arnova8G2** [comment] 2023-06-29 17:12
Thanks @Aarqw12  and @cyberphantom52 , I close this issue

**Closed by Arnova8G2** 2023-06-29 17:12 UTC
